/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMyUmlDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage.eINSTANCE);
		return result;
	}
}
