/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.parser.antlr;

import com.google.inject.Inject;
import lsi.us.es.mis.xtext.parser.antlr.internal.InternalMyUmlDslParser;
import lsi.us.es.mis.xtext.services.MyUmlDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyUmlDslParser extends AbstractAntlrParser {

	@Inject
	private MyUmlDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyUmlDslParser createParser(XtextTokenStream stream) {
		return new InternalMyUmlDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Uml";
	}

	public MyUmlDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyUmlDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
