/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyUmlDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("lsi/us/es/mis/xtext/parser/antlr/internal/InternalMyUmlDsl.tokens");
	}
}
