/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.ui.tests;

import com.google.inject.Injector;
import lsi.us.es.mis.xtext.myuml.ui.internal.MyumlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyUmlDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MyumlActivator.getInstance().getInjector("lsi.us.es.mis.xtext.MyUmlDsl");
	}

}
