/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lsi.us.es.mis.xtext.MyUmlDslRuntimeModule;
import lsi.us.es.mis.xtext.MyUmlDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyUmlDslIdeSetup extends MyUmlDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyUmlDslRuntimeModule(), new MyUmlDslIdeModule()));
	}
	
}
