/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.ui;

import com.google.inject.Injector;
import lsi.us.es.mis.xtext.myuml.ui.internal.MyumlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyUmlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MyumlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MyumlActivator activator = MyumlActivator.getInstance();
		return activator != null ? activator.getInjector(MyumlActivator.LSI_US_ES_MIS_XTEXT_MYUMLDSL) : null;
	}

}
