/**
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.myUmlDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cardinality</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMin <em>Min</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMax <em>Max</em>}</li>
 * </ul>
 *
 * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getCardinality()
 * @model
 * @generated
 */
public interface Cardinality extends EObject
{
  /**
   * Returns the value of the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min</em>' attribute.
   * @see #setMin(int)
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getCardinality_Min()
   * @model
   * @generated
   */
  int getMin();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMin <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min</em>' attribute.
   * @see #getMin()
   * @generated
   */
  void setMin(int value);

  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(String)
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getCardinality_Max()
   * @model
   * @generated
   */
  String getMax();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(String value);

} // Cardinality
