/**
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.myUmlDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyUmlDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myUmlDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.us.lsi/es/mis/xtext/MyUmlDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myUmlDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyUmlDslPackage eINSTANCE = lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl.init();

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.UmlImpl <em>Uml</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.UmlImpl
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getUml()
   * @generated
   */
  int UML = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UML__ENTITIES = 0;

  /**
   * The feature id for the '<em><b>Relationships</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UML__RELATIONSHIPS = 1;

  /**
   * The number of structural features of the '<em>Uml</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UML_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.EntityImpl
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__ATTRIBUTES = 1;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.AttributeImpl
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.RelationshipImpl <em>Relationship</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.RelationshipImpl
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getRelationship()
   * @generated
   */
  int RELATIONSHIP = 3;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__SOURCE = 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__TARGET = 1;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__ROLE = 2;

  /**
   * The feature id for the '<em><b>Cardinality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP__CARDINALITY = 3;

  /**
   * The number of structural features of the '<em>Relationship</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONSHIP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.CardinalityImpl <em>Cardinality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.CardinalityImpl
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getCardinality()
   * @generated
   */
  int CARDINALITY = 4;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARDINALITY__MIN = 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARDINALITY__MAX = 1;

  /**
   * The number of structural features of the '<em>Cardinality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARDINALITY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link lsi.us.es.mis.xtext.myUmlDsl.PrimitiveType <em>Primitive Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see lsi.us.es.mis.xtext.myUmlDsl.PrimitiveType
   * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getPrimitiveType()
   * @generated
   */
  int PRIMITIVE_TYPE = 5;


  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.myUmlDsl.Uml <em>Uml</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uml</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Uml
   * @generated
   */
  EClass getUml();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.myUmlDsl.Uml#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Uml#getEntities()
   * @see #getUml()
   * @generated
   */
  EReference getUml_Entities();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.myUmlDsl.Uml#getRelationships <em>Relationships</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Relationships</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Uml#getRelationships()
   * @see #getUml()
   * @generated
   */
  EReference getUml_Relationships();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.myUmlDsl.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.myUmlDsl.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for the containment reference list '{@link lsi.us.es.mis.xtext.myUmlDsl.Entity#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Entity#getAttributes()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Attributes();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.myUmlDsl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.myUmlDsl.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.myUmlDsl.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Type();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship <em>Relationship</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relationship</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Relationship
   * @generated
   */
  EClass getRelationship();

  /**
   * Returns the meta object for the reference '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Relationship#getSource()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Source();

  /**
   * Returns the meta object for the reference '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Relationship#getTarget()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Target();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Relationship#getRole()
   * @see #getRelationship()
   * @generated
   */
  EAttribute getRelationship_Role();

  /**
   * Returns the meta object for the containment reference '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getCardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cardinality</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Relationship#getCardinality()
   * @see #getRelationship()
   * @generated
   */
  EReference getRelationship_Cardinality();

  /**
   * Returns the meta object for class '{@link lsi.us.es.mis.xtext.myUmlDsl.Cardinality <em>Cardinality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cardinality</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Cardinality
   * @generated
   */
  EClass getCardinality();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMin()
   * @see #getCardinality()
   * @generated
   */
  EAttribute getCardinality_Min();

  /**
   * Returns the meta object for the attribute '{@link lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.Cardinality#getMax()
   * @see #getCardinality()
   * @generated
   */
  EAttribute getCardinality_Max();

  /**
   * Returns the meta object for enum '{@link lsi.us.es.mis.xtext.myUmlDsl.PrimitiveType <em>Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Primitive Type</em>'.
   * @see lsi.us.es.mis.xtext.myUmlDsl.PrimitiveType
   * @generated
   */
  EEnum getPrimitiveType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyUmlDslFactory getMyUmlDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.UmlImpl <em>Uml</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.UmlImpl
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getUml()
     * @generated
     */
    EClass UML = eINSTANCE.getUml();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UML__ENTITIES = eINSTANCE.getUml_Entities();

    /**
     * The meta object literal for the '<em><b>Relationships</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UML__RELATIONSHIPS = eINSTANCE.getUml_Relationships();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.EntityImpl
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__ATTRIBUTES = eINSTANCE.getEntity_Attributes();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.AttributeImpl
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.RelationshipImpl <em>Relationship</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.RelationshipImpl
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getRelationship()
     * @generated
     */
    EClass RELATIONSHIP = eINSTANCE.getRelationship();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__SOURCE = eINSTANCE.getRelationship_Source();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__TARGET = eINSTANCE.getRelationship_Target();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONSHIP__ROLE = eINSTANCE.getRelationship_Role();

    /**
     * The meta object literal for the '<em><b>Cardinality</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONSHIP__CARDINALITY = eINSTANCE.getRelationship_Cardinality();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.myUmlDsl.impl.CardinalityImpl <em>Cardinality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.CardinalityImpl
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getCardinality()
     * @generated
     */
    EClass CARDINALITY = eINSTANCE.getCardinality();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARDINALITY__MIN = eINSTANCE.getCardinality_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARDINALITY__MAX = eINSTANCE.getCardinality_Max();

    /**
     * The meta object literal for the '{@link lsi.us.es.mis.xtext.myUmlDsl.PrimitiveType <em>Primitive Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see lsi.us.es.mis.xtext.myUmlDsl.PrimitiveType
     * @see lsi.us.es.mis.xtext.myUmlDsl.impl.MyUmlDslPackageImpl#getPrimitiveType()
     * @generated
     */
    EEnum PRIMITIVE_TYPE = eINSTANCE.getPrimitiveType();

  }

} //MyUmlDslPackage
