/**
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.myUmlDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getSource <em>Source</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getTarget <em>Target</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getRole <em>Role</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getCardinality <em>Cardinality</em>}</li>
 * </ul>
 *
 * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getRelationship()
 * @model
 * @generated
 */
public interface Relationship extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Entity)
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getRelationship_Source()
   * @model
   * @generated
   */
  Entity getSource();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Entity value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(Entity)
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getRelationship_Target()
   * @model
   * @generated
   */
  Entity getTarget();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(Entity value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' attribute.
   * @see #setRole(String)
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getRelationship_Role()
   * @model
   * @generated
   */
  String getRole();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getRole <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' attribute.
   * @see #getRole()
   * @generated
   */
  void setRole(String value);

  /**
   * Returns the value of the '<em><b>Cardinality</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cardinality</em>' containment reference.
   * @see #setCardinality(Cardinality)
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getRelationship_Cardinality()
   * @model containment="true"
   * @generated
   */
  Cardinality getCardinality();

  /**
   * Sets the value of the '{@link lsi.us.es.mis.xtext.myUmlDsl.Relationship#getCardinality <em>Cardinality</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cardinality</em>' containment reference.
   * @see #getCardinality()
   * @generated
   */
  void setCardinality(Cardinality value);

} // Relationship
