/**
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.myUmlDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uml</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Uml#getEntities <em>Entities</em>}</li>
 *   <li>{@link lsi.us.es.mis.xtext.myUmlDsl.Uml#getRelationships <em>Relationships</em>}</li>
 * </ul>
 *
 * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getUml()
 * @model
 * @generated
 */
public interface Uml extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.myUmlDsl.Entity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getUml_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

  /**
   * Returns the value of the '<em><b>Relationships</b></em>' containment reference list.
   * The list contents are of type {@link lsi.us.es.mis.xtext.myUmlDsl.Relationship}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationships</em>' containment reference list.
   * @see lsi.us.es.mis.xtext.myUmlDsl.MyUmlDslPackage#getUml_Relationships()
   * @model containment="true"
   * @generated
   */
  EList<Relationship> getRelationships();

} // Uml
