/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyUmlDslStandaloneSetup extends MyUmlDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MyUmlDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
