/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyUmlDslRuntimeModule extends AbstractMyUmlDslRuntimeModule {
}
